### ISSUE TITLE
Crash in 1.18.1 Forge

### ISSUE THREAD

**Issue by Oscillate18** [ferriarnus/EnderBundle#1]
Game crashes when the ender hopper is placed, log attached.
[crash-2022-01-29_20.29.58-client.txt](https://github.com/ferriarnus/EnderBundle/files/7964669/crash-2022-01-29_20.29.58-client.txt)

**Comment by ferriarnus** [comment]
Thank you for the report. Should be fix in the new version. It should be online in a couple of hours.
https://www.curseforge.com/minecraft/mc-mods/ender-bundle/files/3629401 @Oscillate18

**Comment by Oscillate18** [comment]
Thank you so much for the fix! What an awesome mod, goes perfect in my Vanilla+ pack.

**Comment by ferriarnus** [comment]
You're welcome, glad you like the mod!
