### ISSUE TITLE
compatibility with other mods

### ISSUE THREAD

**Issue by jett42069** [ferriarnus/EnderBundle#2]
I have a ton of mods installed and haven't been able to pinpoint which one conflicts.

crash log--
https://pastebin.com/FZkqyDh3

**Comment by ferriarnus** [comment]
@jett42069 thank you for making this issue. I think I know where I went wrong and I'll push a fix right now (version 1.0.2). Can you tell me if that fixes it?

**Comment by jett42069** [comment]
> @jett42069 thank you for making this issue. I think I know where I went wrong and I'll push a fix right now (version 1.0.2). Can you tell me if that fixes it?

that fixed it! thank you!

**Comment by ferriarnus** [comment]
Great, thanks again for reporting it!
