### ISSUE TITLE
Missing Background on GUI & Mark 1.18.2 Compatability?

### ISSUE THREAD

**Issue by Oscillate18** [ferriarnus/EnderBundle#3]
The GUI is missing the dark background applied to all others, would it be possible for this to be implemented? It's very minor but does look a little odd. The mod is also 1.18.2 compatible from my testing, so you might want to mark it compatible on curseforge so that others on this version can find it. It definitely deserves more attention, keep up the good work!

Screenshots:
![2022-04-02_21 45 38](https://user-images.githubusercontent.com/65877846/161400677-03360af7-dd86-474c-af28-4c7b159779a8.png)
![2022-04-02_21 45 42](https://user-images.githubusercontent.com/65877846/161400680-62fa7482-7c25-4812-beab-df231854cd18.png)
![2022-04-02_21 45 53](https://user-images.githubusercontent.com/65877846/161400683-9d71ae74-01a4-4646-b67e-0b657b835f31.png)

**Comment by ferriarnus** [comment]
Sorry for the (very) late reply. I'm a bit busy irl, but I'll try to update it!
