### ISSUE TITLE
Crash on world load in 1.18.2

### ISSUE THREAD

**Issue by Warhand** [ferriarnus/EnderBundle#4]
My world was previously loading fine until I installed ender bundle version 1.10, then it crashed on load with this crashlog.

https://pastebin.com/iFCpS6hK

Ender bundle is one of the first mods mentioned in the crash log, so I imagine its the culprit, and figured I'd report it.

**Comment by ferriarnus** [comment]
Thanks for the report. It seems Immersive engineering doesn't play nice with my recipe. I can't actually recreate the crash, but from the report it seems there is a null where it shouldn't be possible. I've made a protection against that, so it should work. Can you confirm it worked?

**Comment by Warhand** [comment]
Hmm, alright, I'll try and figure out the minimum amount of mods I can
replicate the issue with tomorrow.
