### ISSUE TITLE
Bundle and hopper become unlinked often. Forge 1.18.2

### ISSUE THREAD

**Issue by SodiumShine** [ferriarnus/EnderBundle#7]
I don't know under what circumstances this actually occurs so this ticket  might not be that helpful, but the bundle and hopper keep becoming unlinked. I have the chunk forceloaded to make sure the hopper is always loaded too. Having some kind of indicator or feedback would go a long way to identifying the issue, like a tooltip on the bundle that shows the hopper coordinates, or a chat message if the hopper goes missing, etc.

**Comment by ferriarnus** [comment]
I'll have a look if I can find something.

**Comment by SodiumShine** [comment]
I'm sorry, I've come to realise the issue was indeed due to the mod being incompatible with creative mod as stated on the curse forge page.
I didn't realise this meant switching between creative and other modes would break the link, rather I thought it would simply not be usable for the duration of being in creative mode and work fine after switching back
