### ISSUE TITLE
Crashes on a server 1.19

### ISSUE THREAD

**Issue by Vexxen1** [ferriarnus/EnderBundle#8]
It crashed on a server, and in all the logs, i only found this: minecraft crash io.netty.handler.codec.EncoderException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

It was fixed when i removed the mod, not sure if it was due too a incompatability with another mod, but it worked fine on the client

**Comment by ferriarnus** [comment]
Oh that's not good. Can you send the full report?

**Comment by ferriarnus** [comment]
I think this issue will be resolved in the next release
